name: ThanksgivingEvent
main: dev.jsinco.luma.ThanksgivingEvent
version: '1.0-SNAPSHOT'
api-version: 1.21
author: jsinco
commands:
  event:
    description: Thanksgiving Event Command
softdepend:
  - LumaItems
  - JetsPrisonMines